//Package services generated by service-enroll-generate.go;
// !DO NOT EDIT THIS FILE!
package service

import (
	
	"backend/serve/login" //login ,  auth, , XUnion@GMail.com
	"backend/serve/usermanage" //user ,  auth, , XUnion@GMail.com
	"backend/serve/xxx" //xxx ,  xxx, , XUnion@GMail.com
)

//Enroll will be called from serve cmd
func Enroll(){
  login.Enroll(`{"name":"auth","email":"XUnion@GMail.com"}`)
  usermanage.Enroll(`{"name":"auth","email":"XUnion@GMail.com"}`)
  xxx.Enroll(`{"name":"xxx","email":"XUnion@GMail.com"}`)
}
